-- Exam-alignment pass: patches Module 2 and Module 7 lesson content against
-- the official RST workbook and a set of past assessment papers. Updates 6
-- existing lessons (one also gets a new title) and inserts 1 new lesson.
-- Safe to run once against the live database.
do $$
declare
  v_module_id bigint;
begin
  select id into v_module_id from modules where sort_order = 2;
  if v_module_id is null then raise exception 'module sort_order % not found', 2; end if;
  update lessons set content = 'As skipper, you carry a duty of care for everyone on your vessel and everyone else sharing the water with you. That''s the starting point for everything in this module — the rules exist because a boat is a powerful, sometimes dangerous thing, and someone has to be answerable for how it''s used.

Marine safety officers and police have the power to stop and check vessels, and you''re required to identify yourself as the skipper when asked. If you change your name or address, you need to update your RST details with DTMI.

If you''re involved in a marine incident, there are reporting obligations. Any accident involving serious injury or death, or damage that makes a vessel unseaworthy or unsafe, must be reported to DTMI within 72 hours.

You also have a legal obligation to assist people in distress — but it''s **not an absolute duty**. You don''t have to help if you''re genuinely unable to (say, the call for help came from too far away for you to reach), if an emergency service such as marine rescue has already taken over, or if the circumstances would make helping too dangerous for you or your passengers. And if you do respond to another vessel''s call for help and it''s still afloat with everyone safe, your obligation is to help save life, not to tow them home — offering to stand by until marine rescue arrives is enough.

Alcohol and drugs are treated the same way on the water as on the road — the blood alcohol limit for skippers is 0.05, aligned with WA''s road law, and operating under the influence of illicit drugs carries the same seriousness as drink driving.' where module_id = v_module_id and sort_order = 1;
  select id into v_module_id from modules where sort_order = 2;
  if v_module_id is null then raise exception 'module sort_order % not found', 2; end if;
  update lessons set content = 'Speed limits on the water exist to protect people, property and the environment, and they show up in a few recurring situations worth knowing precisely, not just approximately. Without DTMI''s approval, 8 knots is the limit through the arch of a bridge (unless water skiing is specifically permitted there), in or through a mooring area, in any water less than 3 metres deep, and within **15 metres** of a vessel that''s underway. That distance opens right up to **50 metres** around a moored vessel, a person in the water, a jetty or wharf, or a river bank — two genuinely different figures for two different situations, and an easy pair to mix up. Marine safety signs will tell you the specific limit for a given area, so it pays to know how to read them.

Right of way at jetties follows a similar logic to giving way on the water generally: the vessel travelling down-river usually gives way, a boat on the outer course gives way to one on the inner course, and whoever got underway first generally has the right of way.

You''re also required to keep clear of navigation aids (don''t obstruct them), and crab pots, cray pots, fishing nets, marker buoys and other buoyed gear are banned outright in any channel, fairway or passage without DTMI''s permission — even where there seems to be plenty of room. Stay within the hull of your vessel while underway too — no perching on the bow or gunwales. Marine animals and their habitat get specific protection: anchoring in a way that damages seagrass, disturbing wildlife, or excessive noise and wake near sensitive areas can all be enforcement matters, not just courtesy issues.' where module_id = v_module_id and sort_order = 2;
  select id into v_module_id from modules where sort_order = 2;
  if v_module_id is null then raise exception 'module sort_order % not found', 2; end if;
  update lessons set content = 'Polluting WA''s waterways carries serious penalties — up to $200,000 for an individual and $1 million for a company — so the rules here aren''t just guidelines. Oil, other noxious substances, and plastic (including synthetic rope and fishing line) can **never be dumped, at any distance from shore** — there''s no "far enough out" exception, which is a common trap. Ordinary rubbish and garbage are treated differently: floating rubbish can''t be dumped within 25 nautical miles of land, and food waste, paper, rags, glass or metal can''t go over within 12 nautical miles — or 3 nautical miles if it''s first been through an approved grinder.

Refuelling is one of the most common ways fuel ends up in the water, so take care: know how much fuel you need before you start (leaving room for expansion so you don''t overfill), never leave the filling nozzle unattended, and listen for fuel "blowing back" from the tank breather so you can slow the flow in time. Spills and illegal dumping of oil or noxious substances must be reported to DTMI — call the Oil Spill Response Coordination Unit on (08) 9480 9924, and be ready to give the time and location, the offending vessel''s details, and the type and extent of the pollution.

Sewage discharge from vessels is also regulated, particularly in sensitive or enclosed waterways, so check the rules for the area you''re operating in if your vessel has onboard toilet facilities.' where module_id = v_module_id and sort_order = 3;
  select id into v_module_id from modules where sort_order = 2;
  if v_module_id is null then raise exception 'module sort_order % not found', 2; end if;
  update lessons set title = 'Registration, diving and personal watercraft', content = 'Most recreational vessels with an engine need to be registered, though there are exemptions — small tenders, canoes, and lifeboats used only for their intended purpose are common examples, generally where the vessel is 3.1 metres or less, or fitted with a motor of 5 hp or less. Once registered, your numbers need to be clearly displayed on both sides of the hull, and the registration label — the sticker showing your expiry date — must be fixed on the **port side**, next to the numbers.

Diving has its own signal requirements: a vessel with divers operating from it must fly the International Code Flag "A" (a white and blue swallow-tailed flag, at least 750mm by 600mm), and a diver operating without a vessel — say, from a jetty — must display the same flag. Other vessels need to stay at least 50 metres clear of any dive flag or diving signal; where that''s genuinely not possible, you must slow to a safe speed, proceed with caution, and keep a sharp lookout for people in the water.

Personal watercraft (PWC) — jet skis — count as motor boats under the rules, so the same age, safety equipment and registration requirements apply to them as to any other powered vessel. On top of that, freestyling, wake jumping and similar unpredictable riding (doughnuts, 180° turns, hops and jumps) is banned within any speed-restricted area, within 30 metres of another PWC, and within 50 metres of any other vessel or person in the water — three different distances, so don''t assume they''re all the same.' where module_id = v_module_id and sort_order = 4;
  select id into v_module_id from modules where sort_order = 2;
  if v_module_id is null then raise exception 'module sort_order % not found', 2; end if;
  insert into lessons (module_id, title, content, video_url, sort_order) values (v_module_id, 'Water skiing rules', 'Towing a water skier brings a detailed set of extra rules on top of the ordinary collision regulations, which still apply in full — a ski boat has no priority over a vessel simply passing through a ski area.

Roles matter here. The observer must be at least 14 (see Module 1 for the full set of age rules around skiing), and has the specific job of watching the skier and warning the skipper about vessels approaching from behind — not just "keeping an eye out" generally. The skier themselves can be any age, though wearing an approved Level 50 or 50S lifejacket is recommended. You can only ski in a gazetted ski area, during the permitted times, and in the marked direction, so check the signage at the boat ramp before you start.

There''s also a standard set of hand signals worth knowing cold, since they turn up in the assessment: the observer holds one arm straight up to signal that a skier is down in the water; a skier who''s fallen but is unhurt raises both arms to show they''re OK; and the driver signals they''re bringing the skier in to shore by raising and lowering one hand above their head.

A few distances are worth memorising precisely. Stay at least 50 metres directly behind a skier or a vessel being towed. Don''t tow a skier within 30 metres of the shore or of any landing or take-off area, except while actually landing or taking off — and once you''ve dropped a skier off, keep going for at least 60 metres before stopping to retrieve the ski line, then keep your speed under 8 knots as you head in. A skipper about to take off with a skier must give way to a boat that''s coming in to land one, not the other way around.', null, 5);
  select id into v_module_id from modules where sort_order = 7;
  if v_module_id is null then raise exception 'module sort_order % not found', 7; end if;
  update lessons set content = 'A marine radio is essential safety equipment, and it''s required if you go more than 4 nautical miles from shore in unprotected waters — a mobile phone is a useful backup but cannot replace it, partly because other vessels can''t hear a phone call and partly because a radio is far easier for search and rescue to locate. VHF is the most common choice: the emergency and calling channel is 16, with channel 67 as a supplementary distress channel.

There are three levels of urgency in radio calls. "Mayday" is used only when a vessel is in grave and imminent danger and needs immediate assistance — state your position, your problem, and the number of people on board (the "3 Ps"), repeating until answered. "Pan Pan" is used when the situation is urgent but not immediately life-threatening — a mechanical breakdown or a medical issue, for example. "Securite" (say-cure-i-tay) is used to broadcast an important safety or navigational warning, not a personal emergency.

Beyond a radio call, there''s a recognised set of other distress signals worth knowing, since the assessment can test them individually: a gun or other explosive signal fired at roughly one-minute intervals, the continuous sounding of a fog horn, slowly raising and lowering outstretched arms, smoke or flames on a vessel, the international code flags N over C, and of course a red flare or an orange smoke flare.

Logging on and off with a marine rescue group, or telling a responsible person your plans, is genuinely one of the most important safety habits you can build — it''s serious enough that it''s tested in the practical assessment. Give them the vessel''s details, your departure time and location, destination, trip intentions, number of people aboard, fuel carried, and your estimated time of return — then make sure you actually contact them again when you''re back, so a search doesn''t get triggered unnecessarily.' where module_id = v_module_id and sort_order = 3;
  select id into v_module_id from modules where sort_order = 7;
  if v_module_id is null then raise exception 'module sort_order % not found', 7; end if;
  update lessons set content = 'A bailer or bilge pump isn''t legally required, but it''s recommended for every vessel — even a bucket with two metres of rope attached is a genuinely useful piece of safety gear, for bailing and for fighting small fires. If you fit an electric bilge pump, it should have an indicator showing when it''s running, and its intake should be protected by a strainer to stop it clogging.

Fire extinguishers aren''t mandatory either, but they''re recommended for any vessel with an inboard engine or cooking, heating or cooling equipment that uses flame. Dry powder is the most common all-rounder, but it''s not universal — an ABE-rated dry powder extinguisher isn''t the right choice for a cooking oil or fat fire, which calls for a fire blanket instead, and plain water should never go near an electrical or cooking-oil fire. Get extinguishers inspected at least every six months, and recharge one if the security seal is broken or the gauge isn''t sitting in the green sector — a CO2 extinguisher doesn''t have a gauge, so it''s checked by weight instead, and needs recharging once it''s lost more than 10% of its charged weight. Give a dry powder extinguisher an occasional shake too, to stop the powder compacting inside.

An anchor and enough line to suit the depths you operate in is also recommended. The choice of anchor design is up to you (Danforth, plough, admiralty pattern and others all have their strengths — a Danforth is a solid choice for a small boat over a sandy bottom), but the rule of thumb for how much line to pay out — the "scope" — is at least five times the water depth in calm conditions, more like seven to nine times in fresh or moderate conditions. The chain between the anchor and the rope isn''t just there to resist chafe — its weight acts as a shock absorber that helps the anchor bite and hold. Lower the anchor by letting it run out while moving slowly astern, rather than throwing it forward or motoring ahead as it drops, and once it''s set, check you''re not dragging by taking a bearing or transit on a fixed object on shore and watching for it to change. Anchoring is prohibited in channels and near submarine cables, discouraged in mooring areas where you could foul other vessels'' ground tackle, and best done over sand rather than seagrass or reef where you have the choice.' where module_id = v_module_id and sort_order = 4;
end $$;
